services:
    david63.disableext.admin.controller:
        class: david63\disableext\controller\admin_controller
        arguments:
            - '@config'
            - '@dbal.conn'
            - '@request'
            - '@template'
            - '@user'
            - '@language'
            - '@log'
            - '@cache'
            - '@ext.manager'
