services:
    tatiana5.profilesideswitcher.listener:
        class: tatiana5\profilesideswitcher\event\listener
        arguments:
        - '@config'
        - '@template'
        - '@user'
        - '@dbal.conn'
        - '@request'
        - '%core.root_path%'
        - '%core.php_ext%'
        tags:
            - { name: event.listener }
